version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: marketplace_postgres_db
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgrespass}
      POSTGRES_DB: ${DATABASE_NAME:-myapp}
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"                       # expõe a porta no host
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    restart: unless-stopped

volumes:
  postgres_data: