# prometheus.yml (no mesmo diretório do docker-compose.yml)
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nestjs-app'
    metrics_path: /observability
    static_configs:
      - targets: ['192.168.34.217:3333']
